import 'package:hive/hive.dart';
import '../models/character.dart';

// These adapter classes should be used instead of the ones generated by Hive
// since we're manually implementing the adapters
class ManualCharacterAdapter extends TypeAdapter<Character> {
  @override
  final int typeId = 0;

  @override
  Character read(BinaryReader reader) {
    final id = reader.readInt();
    final name = reader.readString();
    final status = reader.readString();
    final species = reader.readString();
    final type = reader.readString();
    final gender = reader.readString();
    final origin = reader.read() as Origin;
    final location = reader.read() as Location;
    final image = reader.readString();
    final episode = (reader.readList()).cast<String>();
    final url = reader.readString();
    final created = reader.readString();

    return Character(
      id: id,
      name: name,
      status: status, 
      species: species,
      type: type,
      gender: gender,
      origin: origin,
      location: location,
      image: image,
      episode: episode,
      url: url,
      created: created,
    );
  }

  @override
  void write(BinaryWriter writer, Character obj) {
    writer.writeInt(obj.id);
    writer.writeString(obj.name);
    writer.writeString(obj.status);
    writer.writeString(obj.species);
    writer.writeString(obj.type);
    writer.writeString(obj.gender);
    writer.write(obj.origin);
    writer.write(obj.location);
    writer.writeString(obj.image);
    writer.writeList(obj.episode);
    writer.writeString(obj.url);
    writer.writeString(obj.created);
  }
}

class ManualOriginAdapter extends TypeAdapter<Origin> {
  @override
  final int typeId = 1;

  @override
  Origin read(BinaryReader reader) {
    final name = reader.readString();
    final url = reader.readString();

    return Origin(
      name: name,
      url: url,
    );
  }

  @override
  void write(BinaryWriter writer, Origin obj) {
    writer.writeString(obj.name);
    writer.writeString(obj.url);
  }
}

class ManualLocationAdapter extends TypeAdapter<Location> {
  @override
  final int typeId = 2;

  @override
  Location read(BinaryReader reader) {
    final name = reader.readString();
    final url = reader.readString();

    return Location(
      name: name,
      url: url,
    );
  }

  @override
  void write(BinaryWriter writer, Location obj) {
    writer.writeString(obj.name);
    writer.writeString(obj.url);
  }
}